exec-once = hyprdynamicmonitors run --enable-lid-events --debug > /tmp/hdm.log 2>&1

exec-once = waybar
#exec-once = hyprlock || hyprctl dispatch exit
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = trayscale --hide-window

exec-once = elephant
exec-once = walker --gapplication-service
