exec-once = hyprdynamicmonitors run --config /etc/xdg/hyprdynamicmonitors/config.toml --enable-lid-events
exec-once = waybar
#exec-once = hyprlock || hyprctl dispatch exit
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = trayscale --hide-window

exec-once = elephant
exec-once = walker --gapplication-service
