#monitor = DP-1, 2560x1440@99.95Hz, 2560x0, 1.6
monitor = eDP-1,2880x1800@120.00100,0x0,2

bindl = ,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1,disable"
bindl = ,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1,2880x1800@120.00100,0x0,2"
#monitor = eDP-1, disable

env = GDK_SCALE,2
env = GDK_DPI_SCALE,0.5
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
