# Installer script as a flake package: `nix run .#install` (or `nix run 'git+...#install'`
# from the installer ISO).
# Asks for disk, user password and LUKS passphrase, then installs and
# copies the repo to /persistent/etc/nixos on the new machine.
{ ... }: {
  perSystem = { pkgs, ... }: {
    packages.install = pkgs.writers.writeBashBin "install" ''
      export PATH=${
        pkgs.lib.makeBinPath [
          pkgs.coreutils
          pkgs.gnugrep
          pkgs.gnused
          pkgs.gawk
          pkgs.git
          pkgs.util-linux
          pkgs.gum
          pkgs.mkpasswd
          pkgs.disko
          pkgs.e2fsprogs # chattr (NOCOW swapfile on btrfs)
          pkgs.nixos-install-tools
        ]
      }:$PATH
      set -euo pipefail

      REPO_URL="''${1:-https://github.com/moreauadrien/nixos}"
      HOST="tallyho"

      die() { gum style --foreground 196 "✗ $*"; exit 1; }
      step() { gum style --border rounded --border-foreground 212 --padding "0 1" "$*"; }

      step "✦ nixos-next installer — $REPO_URL"

      # 1. Clone the repo into a tmpdir (the flake is evaluated from there as root).
      TMP=$(mktemp -d /tmp/nixos-install.XXXXXX)
      LUKS_KEY=/tmp/luks-passphrase
      trap 'rm -rf "$TMP" "$LUKS_KEY"' EXIT
      step "Cloning $REPO_URL into $TMP"
      git clone --depth 1 "$REPO_URL" "$TMP"

      # 2. Pick the install disk.
      DISK=$(
        lsblk -dno NAME,SIZE,TYPE,MODEL | awk '$3 == "disk" { print "/dev/" $1 "  " $2 "  " $4 }' \
          | gum choose --header "Installation disk (will be erased)"
      )
      DISK=''${DISK%%'  '*}
      [ -n "$DISK" ] || die "No disk selected."

      gum confirm --default=false "Erase $DISK and install NixOS ($HOST) on it?" \
        || die "Aborted."

      # 3. Generate the hardware configuration for this machine (--no-filesystems:
      # disk-owned fileSystems would collide with disko's tmpfs / and others).
      step "Generating hardware configuration"
      nixos-generate-config --no-filesystems --show-hardware-config > "$TMP/.hardware-raw.nix"
      {
        echo "# Host hardware: generated by the installer script (do not edit by hand)."
        echo "{ ... }: {"
        echo "  flake.nixosModules.''${HOST}Hardware ="
        cat "$TMP/.hardware-raw.nix"
        echo ";"
        echo "}"
      } > "$TMP/modules/hosts/$HOST/hardware.nix"
      rm "$TMP/.hardware-raw.nix"

      # Point disko at the selected disk (disko-install also overrides it via --disk).
      sed -i "s|device = \"/dev/[a-z0-9]*\"|device = \"$DISK\"|" "$TMP/modules/hosts/$HOST/disko.nix"

      # 4. Conventional commit (identity fallback: git config is absent on a fresh installer).
      git -C "$TMP" config user.name  "$(git config --global user.name  || echo "Adrien Moreau")"
      git -C "$TMP" config user.email "$(git config --global user.email || echo "adrienmoreau@ik.me")"
      git -C "$TMP" add -A
      git -C "$TMP" diff --cached --quiet || git -C "$TMP" commit -m "chore: generate hardware configuration for $HOST"

      # 5. User password: yescrypt hash written to /persistent/passwd on the
      #    installed machine (user.nix points at it via hashedPasswordFile,
      #    so the hash never lands in the repo).
      step "User password (adrien)"
      USER_PASS=$(gum input --password --placeholder "Password for user adrien")
      [ -n "$USER_PASS" ] || die "Empty password."
      [ "$USER_PASS" = "$(gum input --password --placeholder "Confirm password")" ] || die "Passwords differ."
      USER_HASH=$(printf %s "$USER_PASS" | mkpasswd -s -m yescrypt)

      # 6. Disk encryption passphrase, written to a file read by disko
      #    (disko.nix sets passwordFile = /tmp/luks-passphrase).
      step "Disk encryption (LUKS)"
      LUKS_PASS=$(gum input --password --placeholder "LUKS passphrase")
      [ -n "$LUKS_PASS" ] || die "Empty passphrase."
      [ "$LUKS_PASS" = "$(gum input --password --placeholder "Confirm passphrase")" ] || die "Passphrases differ."
      printf %s "$LUKS_PASS" > "$LUKS_KEY"
      chmod 600 "$LUKS_KEY"

      # 7. Partition, format and mount the disk with disko (LUKS passphrase is
      #    read from passwordFile set in disko.nix). Mounting first lets the
      #    installer use disk-backed swap and its own on-disk store.
      #    Note: disko has no "destroy,format" mode, so it's one invocation.
      #    Uses the disko from nixpkgs (same revision as flake.lock) instead
      #    of a mutable github:disko/latest ref.
      step "Partitioning $DISK (disko)"
      sudo disko --flake "$TMP#$HOST" --mode destroy,format,mount

      # The installer runs from RAM (tmpfs capped at 50% of RAM); a full system
      # closure does not fit. Give it disk-backed swap and grow the tmpfs caps.
      step "Preparing installer swap on $DISK"
      sudo mkdir -p /mnt/nix/.installer-swap
      sudo chattr +C /mnt/nix/.installer-swap
      sudo dd if=/dev/zero of=/mnt/nix/.installer-swap/file bs=1M count=16384 status=none
      sudo chmod 600 /mnt/nix/.installer-swap/file
      sudo mkswap /mnt/nix/.installer-swap/file
      sudo swapon /mnt/nix/.installer-swap/file
      sudo mount -o remount,size=100% / 2>/dev/null || true
      sudo mount -o remount,size=100% /nix/.rw-store 2>/dev/null || true

      step "Installing NixOS on $DISK (nixos-install)"
      sudo env NIX_CONFIG="extra-experimental-features = nix-command flakes" \
        nixos-install --flake "$TMP#$HOST" --no-root-passwd

      # 8. Copy the repo and the user password hash to the installed disk
      #    (/persistent subvolume, already mounted at /mnt/persistent by disko).
      step "Copying the repo to /persistent"
      sudo swapoff /mnt/nix/.installer-swap/file || true
      sudo rm -rf /mnt/nix/.installer-swap
      sudo mkdir -p /mnt/persistent/etc/nixos
      sudo cp -r "$TMP"/. /mnt/persistent/etc/nixos/
      printf %s "$USER_HASH" | sudo tee /mnt/persistent/passwd > /dev/null
      sudo chmod 600 /mnt/persistent/passwd
      sudo umount -R /mnt

      gum style \
        --foreground 212 --border double --border-foreground 212 --padding "1 2" \
        "✔ Installation done on $DISK.
      Reboot, unlock the disk with your LUKS passphrase,
      then log in as adrien with the password you chose.
      Your config lives in /etc/nixos (preserved in /persistent)."
    '';
  };
}
