#!/usr/bin/env bash
# Installer for nixos-next, exposed as flake package `install`:
#   nix run 'git+ssh://git@github.com/moreauadrien/nixos.git#install'
# Asks for disk, user password and LUKS passphrase, then installs and
# copies the repo to /persistent/etc/nixos on the new machine.
set -euo pipefail

REPO_URL="${1:-git@github.com:moreauadrien/nixos.git}"
HOST="tallyho"

die() { gum style --foreground 196 "✗ $*"; exit 1; }
step() { gum style --border rounded --border-foreground 212 --padding "0 1" "$*"; }

step "✦ nixos-next installer — $REPO_URL"

# 1. Clone the repo into a tmpdir (the flake is evaluated from there as root).
TMP=$(mktemp -d /tmp/nixos-install.XXXXXX)
trap 'rm -rf "$TMP"' EXIT
step "Cloning $REPO_URL into $TMP"
git clone --depth 1 "$REPO_URL" "$TMP"

# 2. Pick the install disk.
DISK=$(
  lsblk -dno NAME,SIZE,TYPE,MODEL | awk '$3 == "disk" { print "/dev/" $1 "  " $2 "  " $4 }' \
    | gum choose --header "Installation disk (will be erased)"
)
DISK=${DISK%%'  '*}
[ -n "$DISK" ] || die "No disk selected."

gum confirm --default=false "Erase $DISK and install NixOS ($HOST) on it?" \
  || die "Aborted."

# 3. Generate the hardware configuration for this machine (--no-filesystems:
# disk-owned fileSystems would collide with disko's tmpfs / and others).
step "Generating hardware configuration"
nixos-generate-config --no-filesystems --show-hardware-config > "$TMP/.hardware-raw.nix"
{
  echo "# Host hardware: generated by the installer script (do not edit by hand)."
  echo "{ ... }: {"
  echo "  flake.nixosModules.${HOST}Hardware ="
  cat "$TMP/.hardware-raw.nix"
  echo ";"
  echo "}"
} > "$TMP/modules/hosts/$HOST/hardware.nix"
rm "$TMP/.hardware-raw.nix"

# Point disko at the selected disk (disko-install also overrides it via --disk).
sed -i "s|device = \"/dev/[a-z0-9]*\"|device = \"$DISK\"|" "$TMP/modules/hosts/$HOST/disko.nix"

# 4. Conventional commit (identity fallback: git config is absent on a fresh installer).
git -C "$TMP" config user.name  "$(git config --global user.name  || echo "Adrien Moreau")"
git -C "$TMP" config user.email "$(git config --global user.email || echo "adrienmoreau@ik.me")"
git -C "$TMP" add -A
git -C "$TMP" diff --cached --quiet || git -C "$TMP" commit -m "chore: generate hardware configuration for $HOST"

# 5. User password (kept OUT of the commit: written after it, so the hash
#    only lands in /persistent/etc/nixos on the installed machine).
step "User password (adrien)"
USER_PASS=$(gum input --password --placeholder "Password for user adrien")
[ -n "$USER_PASS" ] || die "Empty password."
[ "$USER_PASS" = "$(gum input --password --placeholder "Confirm password")" ] || die "Passwords differ."
HASH=$(echo "$USER_PASS" | openssl passwd -6 -stdin)
sed -i "s|initialPassword = \"adrien\";|hashedPassword = \"$HASH\";|" "$TMP/modules/system/core/user.nix"

# 6. Disk encryption passphrase.
step "Disk encryption (LUKS)"
LUKS_PASS=$(gum input --password --placeholder "LUKS passphrase")
[ -n "$LUKS_PASS" ] || die "Empty passphrase."
[ "$LUKS_PASS" = "$(gum input --password --placeholder "Confirm passphrase")" ] || die "Passphrases differ."

# 7. Install.
# ponytail: the passphrase is piped to disko's interactive prompt (it reads
# twice from stdin); if disko's prompt flow changes, drop the pipe and let
# the user type it at the cryptsetup prompt.
step "Installing NixOS on $DISK (disko-install)"
# NIX_CONFIG propagates through sudo and disko-install's internal nix calls.
printf '%s\n%s\n' "$LUKS_PASS" "$LUKS_PASS" \
  | sudo env NIX_CONFIG="extra-experimental-features = nix-command flakes" \
      nix run 'github:nix-community/disko/latest#disko-install' -- \
      --flake "$TMP#$HOST" --disk main "$DISK"

# 8. Copy the repo to the installed disk.
step "Copying the repo to $DISK"
ROOT_PART=/dev/$(lsblk -lno NAME,TYPE "$DISK" | awk '$2 == "part" { p = $1 } END { print p }')
OPENED=0
if [ ! -e /dev/mapper/cryptroot ]; then
  printf %s "$LUKS_PASS" | sudo cryptsetup luksOpen --key-file=- "$ROOT_PART" cryptroot
  OPENED=1
fi
sudo mount -o subvol=persistent /dev/mapper/cryptroot /mnt
sudo mkdir -p /mnt/etc/nixos
sudo cp -r "$TMP"/. /mnt/etc/nixos/
sudo umount /mnt
[ "$OPENED" = 1 ] && sudo cryptsetup close cryptroot

gum style \
  --foreground 212 --border double --border-foreground 212 --padding "1 2" \
  "✔ Installation done on $DISK.
Reboot, unlock the disk with your LUKS passphrase,
then log in as adrien with the password you chose.
Your config lives in /etc/nixos (preserved in /persistent)."
